### ISSUE TITLE
Killing 'abandoned' processes

### ISSUE THREAD

**Issue by JuanCab** [jupyterhub/the-littlest-jupyterhub#229] opened 2018-11-05 21:55 UTC
In our use mode, students login, use the server, and then log out.  However, many forget to log out and so their single user process continues to run, eating up resources.  It would be an excellent feature if there could be a configurable timeout for a process such that if no activity happens after some set amount of time, the process is killed.  As it is, once a day we have a cronjob that issues a 'killall -p jupyterhub-singleuser'

**Comment by betatim** [comment] 2018-11-06 06:17
#100 is related. There we discussed running the existing JupyterHub culler as an additional systemd unit. Maybe a better way would be as a cron task?

**Comment by yuvipanda** [comment] 2019-05-20 03:54
Closing as a dupe of #100

**Closed by yuvipanda** 2019-05-20 03:54 UTC
