### ISSUE TITLE
How to add custom settings to jupyter_notebook_config.py?

### ISSUE THREAD

**Issue by Thimm** [jupyterhub/the-littlest-jupyterhub#288] opened 2019-03-06 09:57 UTC
I would like to add custom settings to every users jupyter_notebook_config.py. Particularly, for the jupyterlab extension  [jupyterlab templates](https://github.com/timkpaine/jupyterlab_templates). However, I am not able to find the configuration file. If I generate the config file it will only get generated for the current user.

**Comment by yuvipanda** [comment] 2019-04-17 18:56
Heya! You can put the file in any of the paths under 'config' when you run 'jupyter --paths'. For systemwide use, I think /usr/local/etc/jupyter/jupyter_notebook_config.py might be a good place.

**Comment by yuvipanda** [comment] 2019-04-17 18:58
We should document this, since it's probably a common question. Thank you for asking it!

**Comment by yuvipanda** [comment] 2019-05-20 03:45
Closing this as a duplicate of #234

**Closed by yuvipanda** 2019-05-20 03:45 UTC
Labels: needs-documentation
