### ISSUE TITLE
Using dockerSpawner with the littlest jupyter hub

### ISSUE THREAD

**Issue by ludwigsaux** [jupyterhub/the-littlest-jupyterhub#759] opened 2021-11-04 14:04 UTC
Hello,

Bug description
I actually have a problem with my config of the littlest jupyter hub, i want to use dockspawner and wrote this command

tljh-config set spawner.type dockerspawner.DockerSpawner

Expected behaviour
I expected that jupyterhub use dockerSpawner

Actual behaviour
When my jupyter is running, the spawner is traitlets.traitlets.UserCreatingSpawner-4.3.3

Your personal set up
OS:
ubuntu 18.04
Version(s):
jupyterhub 1.4.2
python 3.7
the-littlest-jupyterhub journal

nov. 04 14:08:40 wdyb3089 systemd[1]: Started jupyterhub.service.
nov. 04 14:08:41 wdyb3089 python3[42841]: [I 2021-11-04 14:08:41.357 JupyterHub app:2459] Running JupyterHub version 1.4.2
nov. 04 14:08:41 python3[42841]: [I 2021-11-04 14:08:41.357 JupyterHub app:2490] Using Authenticator: oauthenticator.gitlab.GitLabOAuthenticator-14.2.0
nov. 04 14:08:41 python3[42841]: [I 2021-11-04 14:08:41.357 JupyterHub app:2490] Using Spawner: traitlets.traitlets.UserCreatingSpawner-4.3.3
nov. 04 14:08:41 wdyb3089 python3[42841]: [I 2021-11-04 14:08:41.358 JupyterHub app:2490] Using Proxy: jupyterhub_traefik_proxy.toml.TraefikTomlProxy-0+unknown
nov. 04 14:08:41 wdyb3089 python3[42841]: [I 2021-11-04 14:08:41.366 JupyterHub app:1534] Loading cookie_secret from /opt/tljh/state/jupyterhub_cookie_secret

**Comment by yuvipanda** [comment] 2023-09-29 21:32
Duplicate of https://github.com/jupyterhub/the-littlest-jupyterhub/issues/765

**Closed by yuvipanda** 2023-09-29 21:32 UTC
Labels: bug
