### ISSUE TITLE
Not working with s3contents

### ISSUE THREAD

**Issue by arunhallan** [jupyterhub/the-littlest-jupyterhub#756] opened 2021-11-02 12:23 UTC
Hi,

I have dropped a config file in jupyterhub_config.d with the contents below.

TLJH doesn't load anything from S3.

The file is definitely loaded as I initially got some dependency errors.

Config below:

```
from s3contents import S3ContentsManager
from hybridcontents import HybridContentsManager
from notebook.services.contents.largefilemanager import LargeFileManager


c.NotebookApp.contents_manager_class = HybridContentsManager
c.ServerApp.contents_manager_class = HybridContentsManager

c.HybridContentsManager.manager_classes = {
    "": LargeFileManager,
    "shared": S3ContentsManager,
    # Associate /directory with a LargeFileManager.
    "local": LargeFileManager,
    # "bookstore": BookstoreContentsArchiver
}

c.HybridContentsManager.manager_kwargs = {
    # Args for root S3ContentsManager.
    "shared": {"bucket": "BUCKETNAME"},
    # Args for the LargeFileManager mapped to /directory
    "local": {"root_dir": "/opt"},
    "": {"root_dir": "/opt"},
}

```

**Comment by manics** [comment] 2021-11-02 13:10
It looks like this is a duplicate of https://discourse.jupyter.org/t/using-s3contents-with-tljh/11507/3

**Closed by manics** 2021-11-02 13:10 UTC
Labels: bug

**Comment by arunhallan** [comment] 2021-11-02 13:58
Sorry, I got a bit trigger happy.
