### ISSUE TITLE
No admin users, admin interface will be unavailable

### ISSUE THREAD

**Issue by swallace21** [jupyterhub/the-littlest-jupyterhub#147] opened 2018-08-17 17:47 UTC
On Debian 9 (stretch)

config.yaml
```
root@styx:/opt/tljh/hub/bin# cat /opt/tljh/config.yaml
users:
  admin:
  - sw90
```

groups:
jupyterhub-admins:x:1005:sw90
jupyterhub-users:x:1006:sw90

output:
```
root@styx:/opt/tljh/hub/bin# ./jupyterhub
[I 2018-08-17 13:38:39.538 JupyterHub app:1667] Using Authenticator: jupyterhub.auth.PAMAuthenticator-0.9.1
[I 2018-08-17 13:38:39.538 JupyterHub app:1667] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-0.9.1
[I 2018-08-17 13:38:39.539 JupyterHub app:1014] Loading cookie_secret from /opt/tljh/hub/bin/jupyterhub_cookie_secret
[I 2018-08-17 13:38:39.723 JupyterHub proxy:431] Generating new CONFIGPROXY_AUTH_TOKEN
[W 2018-08-17 13:38:39.725 JupyterHub app:1171] No admin users, admin interface will be unavailable.
[W 2018-08-17 13:38:39.726 JupyterHub app:1172] Add any administrative users to `c.Authenticator.admin_users` in config.
```

**Comment by yuvipanda** [comment] 2018-09-12 23:56
@swallace21 heya! If you're just starting 'jupyterhub' by hand it isn't using any of the config TLJH is setting up. If you do `sudo tljh-config reload` that should restart JupyterHub for the config to take effect. If you wanna peek behind the curtains as such, you can look at `sudo systemctl restart jupyterhub` / `sudo systemctl show jupyterhub` for more information about the systemd units used to start & keep JupyterHub running.

**Comment by GeorgianaElena** [comment] 2020-10-21 10:45
Closing this as the issue is quite old. If you need more help please post on the [Discourse](https://discourse.jupyter.org/) forum. Thanks :sunflower:

**Closed by GeorgianaElena** 2020-10-21 10:45 UTC
Labels: support
