### ISSUE TITLE
PermissionError: [Errno 13] Permission denied:'/usr/local/share/jupyter/nbconvert/templates/html/conf.json'

### ISSUE THREAD

**Issue by k-nayak** [jupyterhub/the-littlest-jupyterhub#693] opened 2021-06-28 12:30 UTC
### Bug description
Unable to create or open existing .ipynb files in Jupyter notebook and JupyterHub 

#### Expected behaviour
Open .ipynb notebooks to run code

#### Actual behaviour
500: internal server error

### Your personal set up

 - OS:
Ubuntu 20.04 running in Virtual box (Host OS: Windows server 2012 R2)
 - Version(s):
jupyterhub --the littlest jupyterhub

```
</details>

- <details><summary>Logs</summary>
<!--
Errors are often logged by jupytehub. How you get logs depends on your deployment.
With kubernetes it might be:

    kubectl get pod # hub pod name starts with hub...
    kubectl logs hub-...
    # or for a single-user server
    kubectl logs jupyter-username

Or the-littlest-jupyterhub:

    journalctl -u jupyterhub
    # or for a single-user server
    journalctl -u jupyter-username
-->

```
(base) nak4si@SI-V-00003:~$ jupyter notebook
[I 13:09:43.734 NotebookApp] Loading IPython parallel extension
[I 2021-06-28 13:09:44.619 LabApp] JupyterLab extension loaded from /home/nak4si/anaconda3/lib/python3.7/site-packages/jupyterlab
[I 2021-06-28 13:09:44.619 LabApp] JupyterLab application directory is /home/nak4si/anaconda3/share/jupyter/lab
[I 13:09:44.626 NotebookApp] Serving notebooks from local directory: /home/nak4si
[I 13:09:44.626 NotebookApp] Jupyter Notebook 6.4.0 is running at:
[I 13:09:44.626 NotebookApp] http://localhost:8888/?token=63b576c9f0edf835009b3d7f129400d6fd4b49eedbfa0292
[I 13:09:44.626 NotebookApp]  or http://127.0.0.1:8888/?token=63b576c9f0edf835009b3d7f129400d6fd4b49eedbfa0292
[I 13:09:44.626 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 13:09:44.699 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/nak4si/.local/share/jupyter/runtime/nbserver-1236502-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=63b576c9f0edf835009b3d7f129400d6fd4b49eedbfa0292
     or http://127.0.0.1:8888/?token=63b576c9f0edf835009b3d7f129400d6fd4b49eedbfa0292
[I 13:09:49.177 NotebookApp] Creating new notebook in 
[E 13:09:49.442 NotebookApp] Uncaught exception GET /notebooks/Untitled4.ipynb?kernel_name=python3 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/notebooks/Untitled4.ipynb?kernel_name=python3', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/nak4si/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/home/nak4si/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 775, in run
        yielded = self.gen.send(value)
      File "/home/nak4si/anaconda3/lib/python3.7/site-packages/notebook/notebook/handlers.py", line 101, in get
        get_frontend_exporters=get_frontend_exporters
      File "/home/nak4si/anaconda3/lib/python3.7/site-packages/notebook/base/handlers.py", line 516, in render_template
        return template.render(**ns)
      File "/home/nak4si/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 1289, in render
        self.environment.handle_exception()
      File "/home/nak4si/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 924, in handle_exception
        raise rewrite_traceback_stack(source=source)
      File "/home/nak4si/anaconda3/lib/python3.7/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/home/nak4si/anaconda3/lib/python3.7/site-packages/notebook/templates/page.html", line 154, in top-level template code
        {% block header %}
      File "/home/nak4si/anaconda3/lib/python3.7/site-packages/notebook/templates/notebook.html", line 115, in block 'header'
        {% for exporter in get_frontend_exporters() %}
      File "/home/nak4si/anaconda3/lib/python3.7/site-packages/notebook/notebook/handlers.py", line 40, in get_frontend_exporters
        for name in get_export_names():
      File "/home/nak4si/.local/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 146, in get_export_names
        e = get_exporter(exporter_name)(config=config)
      File "/home/nak4si/.local/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 103, in get_exporter
        if getattr(exporter(config=config), 'enabled', True):
      File "/home/nak4si/.local/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 330, in __init__
        super().__init__(config=config, **kw)
      File "/home/nak4si/.local/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 114, in __init__
        self._init_preprocessors()
      File "/home/nak4si/.local/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 497, in _init_preprocessors
        conf = self._get_conf()
      File "/home/nak4si/.local/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 517, in _get_conf
        if conf_path.exists():
      File "/home/nak4si/anaconda3/lib/python3.7/pathlib.py", line 1361, in exists
        self.stat()
      File "/home/nak4si/anaconda3/lib/python3.7/pathlib.py", line 1183, in stat
        return self._accessor.stat(self)
    PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter/nbconvert/templates/html/conf.json'
[E 13:09:49.453 NotebookApp] {
      "Host": "localhost:8888",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept-Encoding": "gzip, deflate",
      "Connection": "keep-alive",
      "Referer": "http://localhost:8888/tree",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1624878586|23:username-localhost-8888|44:ZDc4OWZkZjBkMmNmNDY5ZmJkNWYyYWVjYzg4OTI5MTc=|d8140b21cf4a6c3e7f025f703db2b70ad24c70552b3daaa42f8532c052fdf2de\"; _xsrf=2|75f08fec|7fb2f9de88df51d1104947546e40b512|1624604371",
      "Upgrade-Insecure-Requests": "1"
    }
[E 13:09:49.453 NotebookApp] 500 GET /notebooks/Untitled4.ipynb?kernel_name=python3 (127.0.0.1) 233.380000ms referer=http://localhost:8888/tree

(base) nak4si@SI-V-00003:~$ jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : 6.4.0
qtconsole        : 5.1.0
ipython          : 7.22.0
ipykernel        : 5.3.4
jupyter client   : 6.1.12
jupyter lab      : 3.0.14
nbconvert        : 6.1.0
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5

```
</details>

**Comment by manics** [comment] 2021-06-29 17:10
This is a duplicate of https://discourse.jupyter.org/t/500-internal-server-error-while-trying-to-open-python-notebook-on-jupyterhub/9738

**Closed by manics** 2021-06-29 17:10 UTC
Labels: duplicate
