### ISSUE TITLE
Install issues on Ubuntu 18.04

### ISSUE THREAD

**Issue by christasich** [jupyterhub/the-littlest-jupyterhub#502] opened 2020-02-03 18:28 UTC
I'm running into an error when trying to install TLJH on my personal server (Ubuntu Server 18.04.04 LTS) I start by issuing this command on my admin account.

`curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py | sudo -E python3 - --admin chris
`

Here's the terminal output with the error.

```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6354  100  6354    0     0  28115      0 --:--:-- --:--:-- --:--:-- 28115
Checking if TLJH is already installed...
TLJH already installed, upgrading...
Upgrading TLJH installer...
Setup tljh package
Starting TLJH installer...
Setting up admin users
Granting passwordless sudo to JupyterHub admins...
Setting up user environment...
Ran /opt/tljh/user/bin/python -m pip install -r /opt/tljh/hub/lib/python3.6/site-packages/tljh/requirements-base.txt with exit code 1
WARNING: The directory '/home/chris/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/chris/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/opt/tljh/hub/lib/python3.6/site-packages/tljh/requirements-base.txt'

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 508, in <module>
    main()
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 491, in main
    ensure_user_environment(args.user_requirements_txt_url)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 277, in ensure_user_environment
    os.path.join(HERE, 'requirements-base.txt'),
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/conda.py", line 151, in ensure_pip_requirements
    requirements_path
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/utils.py", line 32, in run_subprocess
    raise subprocess.CalledProcessError(cmd=cmd, returncode=proc.returncode)
subprocess.CalledProcessError: Command '['/opt/tljh/user/bin/python', '-m', 'pip', 'install', '-r', '/opt/tljh/hub/lib/python3.6/site-packages/tljh/requirements-base.txt']' returned non-zero exit status 1.
```

I've noticed that within `/opt/tljh/hub/lib/python3.6/site-packages/tljh/` there is no `requirements-base.txt` file. I've tried manually adding it and I end up with a different error. Any advice on how to fix this?

**Comment by manics** [comment] 2020-02-03 19:18
This PR was merged at 17:14 GMT, roughly one hour before you posted the above: https://github.com/jupyterhub/the-littlest-jupyterhub/pull/457

**Comment by Adrast** [comment] 2020-02-04 09:34
I've got the exact same error when trying to install on Ubuntu 18.04 server.

**Comment by manics** [comment] 2020-02-04 10:29
I've reproduced this on a new VM:
```
sudo apt install python3 python3-dev git curl
curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py | sudo -E python3 - --admin admin
```
@GeorgianaElena do you know what the problem could be?

**Comment by bjornarfjelldal** [comment] 2020-02-04 10:56
I get the same exact thing - and I've been busting my head the last 24 hours because I did make a successful install earlier yesterday, and have been doing the exact same approach today. 

Can confirm installing on Ubuntu 18.04 gives this error (and is 100% related to PR #457)

**Comment by GeorgianaElena** [comment] 2020-02-04 11:54
I'm wondering if  not including the requirements file in the manifest is what's causing this. It's very strange however why the tests passed for that PR.

**Comment by GeorgianaElena** [comment] 2020-02-04 11:55
I don't have access to a computer right now :(, but as soon as I can, I will investigate this further.

**Comment by bjornarfjelldal** [comment] 2020-02-04 14:11
That would be great! :)

**Comment by asongtoruin** [comment] 2020-02-04 14:28
Just as a further confirmation - I've encountered the same issue following the [AWS install guide](http://tljh.jupyter.org/en/latest/install/amazon.html) with the same reference to `requirements-base.txt`

**Closed** 2020-02-04 17:41 UTC
Labels: bug
