### ISSUE TITLE
Loading extensions by default 

### ISSUE THREAD

**Issue by biojerm** [jupyterhub/the-littlest-jupyterhub#172] opened 2018-08-31 18:37 UTC
I am trying to use `iPython-file-upload` ([link](https://github.com/peteut/ipython-file-upload)) in my notebooks.  Currently, in order to get the 'Browse' button to appear I have to enable the extension with each user.  

Specifically I have to run these two commands in the notebook terminal 
`$jupyter nbextension install --py fileupload`

`$jupyter nbextension enable --py fileupload`

Is there a way for me to preload each notebook with the `fileupload` extension preloaded and enabled?  I assume there is since the [Binder ](https://beta.mybinder.org/v2/gh/draperjames/fileupload2binder/master?filepath=index.ipynb) page displays the 'Browse' button, however I could not find how to add extensions in the documentation.   The Install [Conda, Pip Apt-packages](https://the-littlest-jupyterhub.readthedocs.io/en/latest/howto/env/user-environment.html#howto-env-user-environment)  looked promising, but I might have missed something.  

Thanks in advance for any help/suggestions

**Comment by yuvipanda** [comment] 2018-09-04 19:17
Thanks for opening this issue!

Try using '--sys-prefix' to both the install and enable commands?

**Comment by biojerm** [comment] 2018-09-05 15:35
Just to be clear should I use `--sys-prefix` flag from the terminal window within a notebook with admin privileges or from a terminal window on the system?  Both?

**Comment by yuvipanda** [comment] 2018-09-06 22:02
@biojerm either should work!

**Comment by GeorgianaElena** [comment] 2020-10-21 11:53
Closing this as the issue is quite old and seems to be resolved. If you need help or have any questions, please post on the [Jupyter Discourse](https://discourse.jupyter.org/) forum. Thanks! :sunflower:

**Closed by GeorgianaElena** 2020-10-21 11:53 UTC
Labels: enhancement
