### ISSUE TITLE
Unable to install git extension on TLJH JupyterLab

### ISSUE THREAD

**Issue by gs-scooter** [jupyterhub/the-littlest-jupyterhub#979] opened 2024-04-18 14:52 UTC
### Bug description

After installing TLJH via the latest bootstrap code, I am unable to get either `jupyterlab-git` or `jupyterlab-github` working as an extension. They appear to install successfully but they do not show up in the UI.

### How to reproduce

1. Attempt installation via pip in `/opt/tljh/hub` venv.
2. Attempt installation via conda in `/opt/tljh/hub` venv.
3. Attempt installation via pip in `/opt/tljh/user` venv.
4. Attempt installation via conda in `/opt/tljh/user` venv.

#### Expected behaviour

The extension's UI panel appears in JupyterLab

#### Actual behaviour

No extension panel appears in the UI.

### Your personal set up
Server extension list:
```
Config dir: /root/.jupyter

Config dir: /opt/tljh/hub/etc/jupyter
    jupyter_lsp enabled
    - Validating jupyter_lsp...
      jupyter_lsp 2.2.5 OK
    jupyter_server_mathjax enabled
    - Validating jupyter_server_mathjax...
      jupyter_server_mathjax  OK
    jupyter_server_terminals enabled
    - Validating jupyter_server_terminals...
      jupyter_server_terminals 0.5.3 OK
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 4.1.6 OK
    jupyterlab_git enabled
    - Validating jupyterlab_git...
      jupyterlab_git 0.50.0 OK
    nbdime enabled
    - Validating nbdime...
      nbdime 4.0.1 OK
    notebook_shim enabled
    - Validating notebook_shim...
      notebook_shim  OK

Config dir: /usr/local/etc/jupyter
```

Lab extension list:
```
JupyterLab v4.1.6
/opt/tljh/hub/share/jupyter/labextensions
        jupyterlab_pygments v0.3.0 enabled OK (python, jupyterlab_pygments)
        nbdime-jupyterlab v3.0.1 enabled OK
        @jupyterlab/git v0.50.0 enabled OK (python, jupyterlab-git)
```

 - OS:
 
Ubuntu 20.04 (jammy)

<details><summary>Full environment</summary>

pip freeze output from /opt/tljh/hub venv:
```
# paste output of `pip freeze` or `conda list` here
aiohttp==3.9.5
aiosignal==1.3.1
alembic==1.13.1
anyio==4.3.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
async-generator==1.10
async-lru==2.0.4
async-timeout==4.0.3
attrs==23.2.0
Babel==2.14.0
backcall==0.2.0
backoff==2.2.1
bcrypt==4.1.2
beautifulsoup4==4.12.3
bleach==6.1.0
blinker==1.7.0
certifi==2024.2.2
certipy==0.1.3
cffi==1.16.0
chardet==3.0.4
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
comm==0.2.2
cryptography==42.0.5
debugpy==1.8.1
decorator==5.1.1
defusedxml==0.7.1
ecdsa==0.19.0
escapism==1.0.1
exceptiongroup==1.2.0
executing==2.0.1
fastjsonschema==2.19.1
Flask==2.3.3
Flask-AWSCognito==1.3
Flask-Cors==3.0.10
Flask-JWT-Extended==4.4.1
fqdn==1.5.1
frozenlist==1.4.1
gitdb==4.0.11
GitPython==3.1.43
greenlet==3.0.3
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
idna==2.8
importlib_metadata==7.1.0
importlib_resources==6.4.0
ipykernel==6.29.4
ipython==8.12.3
isoduration==20.11.0
itsdangerous==2.2.0
jedi==0.19.1
Jinja2==3.1.3
json5==0.9.25
jsonpointer==2.4
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter-server-mathjax==0.2.6
jupyter-telemetry==0.1.0
jupyter_client==8.6.1
jupyter_core==5.7.2
jupyter_server==2.14.0
jupyter_server_terminals==0.5.3
jupyterhub==4.1.5
jupyterhub-firstuseauthenticator==1.0.0
jupyterhub-idle-culler==1.3.1
-e git+https://github.com/izihawa/jwtauthenticator_v2.git@ae3b9af108daec9c6de2806dd4e2e8709b219d96#egg=jupyterhub_jwtauthenticator_v2
jupyterhub-ldapauthenticator==1.3.2
jupyterhub-nativeauthenticator==1.2.0
jupyterhub-systemdspawner==1.0.1
jupyterhub-tmpauthenticator==1.0.0
jupyterhub-traefik-proxy==1.1.0
jupyterlab==4.1.6
jupyterlab_git==0.50.0rc0
jupyterlab_pygments==0.3.0
jupyterlab_server==2.26.0
ldap3==2.9.1
Mako==1.3.3
MarkupSafe==2.1.5
matplotlib-inline==0.1.7
mistune==3.0.2
multidict==6.0.5
nbclient==0.10.0
nbconvert==7.16.3
nbdime==4.0.1
nbformat==5.10.4
nest-asyncio==1.6.0
notebook_shim==0.2.4
oauthenticator==16.3.0
oauthlib==3.2.2
onetimepass==1.0.1
overrides==7.7.0
packaging==24.0
pamela==1.1.0
pandocfilters==1.5.1
parso==0.8.4
passlib==1.7.4
pexpect==4.9.0
pickleshare==0.7.5
pkg_resources==0.0.0
pkgutil_resolve_name==1.3.10
platformdirs==4.2.0
pluggy==1.4.0
prometheus_client==0.20.0
prompt-toolkit==3.0.43
psutil==5.9.8
ptyprocess==0.7.0
pure-eval==0.2.2
pyasn1==0.6.0
pycparser==2.22
pycurl==7.45.3
Pygments==2.17.2
PyJWT==2.8.0
pyOpenSSL==24.1.0
python-dateutil==2.9.0.post0
python-jose==3.3.0
python-json-logger==2.0.7
pytz==2024.1
PyYAML==6.0.1
pyzmq==26.0.0
referencing==0.34.0
requests==2.31.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.18.0
rsa==4.9
ruamel.yaml==0.17.40
ruamel.yaml.clib==0.2.8
Send2Trash==1.8.3
six==1.16.0
smmap==5.0.1
sniffio==1.3.1
soupsieve==2.5
SQLAlchemy==2.0.29
stack-data==0.6.3
terminado==0.18.1
the-littlest-jupyterhub @ git+https://github.com/jupyterhub/the-littlest-jupyterhub.git@fc8e19b1b5663f58f0e7b089903d1d1769db06b8
tinycss2==1.2.1
toml==0.10.2
tomli==2.0.1
tornado==6.4
traitlets==5.14.2
types-python-dateutil==2.9.0.20240316
typing_extensions==4.11.0
uri-template==1.3.0
urllib3==1.25.11
wcwidth==0.2.13
webcolors==1.13
webencodings==0.5.1
websocket-client==1.7.0
Werkzeug==3.0.2
yarl==1.9.4
zipp==3.18.1
```
</details>

<details><summary>Configuration</summary>

Using default spawner from TLJH installation and JWT authenticator.

```python
# jupyterhub_config.py
```
</details>

**Comment by manics** [comment] 2024-04-19 14:59
It looks like this is already being discussed in https://discourse.jupyter.org/t/unable-to-get-jupyterlab-git-extension-working/25237 so I'll close this to avoid duplication of effort. We can reopen it if it's confirmed as a bug.

**Closed** 2024-04-19 14:59 UTC
Labels: bug, duplicate
