### ISSUE TITLE
Circular Reference Jupyterhub/Jupyterhub-singleuser Versions

### ISSUE THREAD

**Issue by NebulousOinkler** [jupyterhub/the-littlest-jupyterhub#574] opened 2020-05-15 22:22 UTC
I’m sure this has been solved before,
But I’m on Ubuntu 20.04 and when trying to run TLJH for the first time, it fails to spawn a session when I log in, citing circular references caused by Jupyterhub’s version being 1.1.0 and Jupyterhub-singleuser being 1.0.0. I’ve tried everything I can google but nothing has worked! Please help, and sorry this is poorly formatted. I’m a first timer

**Comment by GeorgianaElena** [comment] 2020-05-16 10:05
Hey @NebulousOinkler, this is a duplicate of https://github.com/jupyterhub/the-littlest-jupyterhub/issues/572.
Upgrading traefik-proxy to the latest release should solve this issue:
```
/opt/tljh/hub/bin/python3 -m pip install -U jupyterhub-traefik-proxy
systemctl restart traefik
```
Thanks for reporting it :sun_with_face:

**Closed by GeorgianaElena** 2020-05-16 10:05 UTC
