### ISSUE TITLE
Upgrading to Python 3.7

### ISSUE THREAD

**Issue by fm75** [jupyterhub/the-littlest-jupyterhub#250] opened 2018-12-28 13:40 UTC
#247 Suggested that we could easily upgrade to 3.7.

I would suggest that we don't do that until [this TensorFlow issue](https://github.com/tensorflow/tensorflow/issues/20517) is resolved. It is relatively easily to install Tensorflow compatible with the current 3.6 interpreter.

Given its popularity today, I think it would be better to wait on this.

**Comment by yuvipanda** [comment] 2019-05-20 04:16
I think enough time has passed for 3.7 to be the default. However, I am not sure if we should automatically *upgrade* currently existing installations from 3.6 to 3.7. That must surely break things.

**Comment by fm75** [comment] 2019-05-20 11:31
I agree that making it the default should be good. According to the [ release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) TensorFlow now supports version 3.7 "on all operating systems".

**Comment by shireenrao** [comment] 2019-05-24 03:39
I tried to upgrade my python under `/opt/tljh/user/bin/python` using the command 
```
conda install python=3.7.2
```
I can confirm that python got installed fine, but looks like jupyterhub is using python under `/opt/tljh/hub/bin`. which is still at `3.6.7`. So my install is broken. How would one upgrade python under `/opt/tljh/hub/bin`? Here is a snippet from my logs

```
May 24 02:59:52 systemd[1]: Started jupyterhub.service.
May 24 02:59:53 python3[931]: [I 2019-05-24 02:59:53.417 JupyterHub app:1673] Using Authenticator: firstuseauthenticator.firstuseauthenticator.FirstUseAuthenti
May 24 02:59:53 python3[931]: [I 2019-05-24 02:59:53.417 JupyterHub app:1673] Using Spawner: builtins.UserCreatingSpawner
May 24 02:59:53 python3[931]: [I 2019-05-24 02:59:53.418 JupyterHub app:1016] Loading cookie_secret from /opt/tljh/state/jupyterhub_cookie_secret
May 24 02:59:53 python3[931]: [I 2019-05-24 02:59:53.478 JupyterHub app:1201] Not using whitelist. Any authenticated user will be allowed.
May 24 02:59:53 python3[931]: [W 2019-05-24 02:59:53.503 JupyterHub app:1462] abc appears to have stopped while the Hub was down
May 24 02:59:53 python3[931]: [W 2019-05-24 02:59:53.505 JupyterHub app:1462] xyz appears to have stopped while the Hub was down
May 24 02:59:53 python3[931]: [W 2019-05-24 02:59:53.506 JupyterHub app:1462] bleh appears to have stopped while the Hub was down
May 24 02:59:53 python3[931]: [I 2019-05-24 02:59:53.523 JupyterHub app:1855] Hub API listening on http://127.0.0.1:15001/hub/
May 24 02:59:53 python3[931]: [I 2019-05-24 02:59:53.523 JupyterHub app:1870] Not starting proxy
May 24 02:59:53 python3[931]: [I 2019-05-24 02:59:53.524 JupyterHub proxy:301] Checking routes
May 24 02:59:53 python3[931]: [W 2019-05-24 02:59:53.524 JupyterHub proxy:363] Deleting stale route /user/abc/
May 24 02:59:53 python3[931]: [W 2019-05-24 02:59:53.524 JupyterHub proxy:363] Deleting stale route /user/xyz/
May 24 02:59:53 python3[931]: [W 2019-05-24 02:59:53.524 JupyterHub proxy:363] Deleting stale route /user/bleh/
May 24 02:59:53 python3[931]: [I 2019-05-24 02:59:53.545 JupyterHub app:1912] JupyterHub is now running at http://:8000
May 24 03:02:03 python3[931]: [I 2019-05-24 03:02:03.086 JupyterHub log:158] 200 GET /hub/login (@xx.xxx.xxx.xxx) 40.62ms
May 24 03:02:10 python3[931]: [I 2019-05-24 03:02:10.518 JupyterHub base:509] User logged in: abc
May 24 03:02:10 python3[931]: [I 2019-05-24 03:02:10.518 JupyterHub log:158] 302 POST /hub/login?next= -> /user/abc/ (abc@xx.xxx.xxx.xxx) 255.52ms
May 24 03:02:10 python3[931]: [I 2019-05-24 03:02:10.555 JupyterHub log:158] 302 GET /user/abc/ -> /hub/user/abc/ (@xx.xxx.xxx.xxx) 0.44ms
May 24 03:02:10 python3[931]: Running as unit: jupyter-abc.service
May 24 03:02:20 python3[931]: [W 2019-05-24 03:02:20.607 JupyterHub web:1782] 500 GET /hub/user/abc/ (xx.xxx.xxx.xxx): Spawner failed to start [status=1]. The l
May 24 03:02:20 python3[931]: [E 2019-05-24 03:02:20.614 JupyterHub log:150] {
May 24 03:02:20 python3[931]:       "Host": "hub.domain.com",
May 24 03:02:20 python3[931]:       "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari
May 24 03:02:20 python3[931]:       "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchang
May 24 03:02:20 python3[931]:       "Accept-Encoding": "gzip, deflate, br",
May 24 03:02:20 python3[931]:       "Accept-Language": "en-US,en;q=0.9",
May 24 03:02:20 python3[931]:       "Cache-Control": "max-age=0",
May 24 03:02:20 python3[931]:       "Cookie": "jupyterhub-hub-login=\"2|1:0|10:1558666930|20:jupyterhub-hub-login|44:ZzM2N2MT
May 24 03:02:20 python3[931]:       "Referer": "https://hub.domain.com/hub/login",
May 24 03:02:20 python3[931]:       "Upgrade-Insecure-Requests": "1",
May 24 03:02:20 python3[931]:       "X-Forwarded-For": "xx.xxx.xxx.xxx",
May 24 03:02:20 python3[931]:       "X-Forwarded-Host": "hub.domain.com",
May 24 03:02:20 python3[931]:       "X-Forwarded-Port": "443",
May 24 03:02:20 python3[931]:       "X-Forwarded-Proto": "https",
May 24 03:02:20 python3[931]:       "X-Forwarded-Server": "ip-xyz-xyz-xy-xyz",
May 24 03:02:20 python3[931]:       "X-Real-Ip": "xx.xxx.xxx.xxx"
May 24 03:02:20 python3[931]:     }
May 24 03:02:20 python3[931]: [E 2019-05-24 03:02:20.615 JupyterHub log:158] 500 GET /hub/user/abc/ (abc@xx.xxx.xxx.xxx) 10024.47ms
May 24 03:02:28 python3[931]: [I 2019-05-24 03:02:28.049 JupyterHub log:158] 200 GET /hub/home (abc@xx.xxx.xxx.xxx) 13.47ms
May 24 03:02:29 python3[931]: [I 2019-05-24 03:02:29.998 JupyterHub log:158] 302 GET /user/abc/ -> /hub/user/abc/ (@xx.xxx.xxx.xxx) 0.55ms
May 24 03:02:40 python3[931]: [I 2019-05-24 03:02:40.049 JupyterHub base:1022] Pending spawn for abc didn't finish in 10.0 seconds
May 24 03:02:40 python3[931]: [I 2019-05-24 03:02:40.049 JupyterHub base:1028] abc is pending spawn
May 24 03:02:40 python3[931]: [I 2019-05-24 03:02:40.054 JupyterHub log:158] 200 GET /hub/user/abc/ (abc@xx.xxx.xxx.xxx) 10016.74ms
May 24 03:02:40 python3[931]: [W 2019-05-24 03:02:40.398 JupyterHub user:510] abc's server never showed up at http://127.0.0.1:57379/user/abc/ after 30 seconds. Giving up
May 24 03:02:40 python3[931]: [E 2019-05-24 03:02:40.422 JupyterHub gen:593] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn(
May 24 03:02:40 python3[931]:     Traceback (most recent call last):
May 24 03:02:40 python3[931]:       File "/opt/tljh/hub/lib/python3.6/site-packages/tornado/gen.py", line 589, in error_callback
May 24 03:02:40 python3[931]:         future.result()
May 24 03:02:40 python3[931]:       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 636, in finish_user_spawn
May 24 03:02:40 python3[931]:         await spawn_future
May 24 03:02:40 python3[931]:       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/user.py", line 528, in spawn
May 24 03:02:40 python3[931]:         raise e
May 24 03:02:40 python3[931]:       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/user.py", line 502, in spawn
May 24 03:02:40 python3[931]:         resp = await server.wait_up(http=True, timeout=spawner.http_timeout)
May 24 03:02:40 python3[931]:       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/utils.py", line 197, in wait_for_http_server
May 24 03:02:40 python3[931]:         timeout=timeout
May 24 03:02:40 python3[931]:       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/utils.py", line 155, in exponential_backoff
May 24 03:02:40 python3[931]:         raise TimeoutError(fail_message)
May 24 03:02:40 python3[931]:     TimeoutError: Server at http://127.0.0.1:57379/user/abc/ didn't respond in 30 seconds
May 24 03:02:40 python3[931]:
May 24 03:02:40 python3[931]: [E 2019-05-24 03:02:40.428 JupyterHub gen:593] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.fi
May 24 03:02:40 python3[931]:     Traceback (most recent call last):
May 24 03:02:40 python3[931]:       File "/opt/tljh/hub/lib/python3.6/site-packages/tornado/gen.py", line 589, in error_callback
May 24 03:02:40 python3[931]:         future.result()
May 24 03:02:40 python3[931]:       File "/opt/tljh/hub/lib/python3.6/site-packages/tornado/gen.py", line 589, in error_callback
May 24 03:02:40 python3[931]:         future.result()
May 24 03:02:40 python3[931]:       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 636, in finish_user_spawn
May 24 03:02:40 python3[931]:         await spawn_future
May 24 03:02:40 python3[931]:       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/user.py", line 528, in spawn
May 24 03:02:40 python3[931]:         raise e
May 24 03:02:40 python3[931]:       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/user.py", line 502, in spawn
May 24 03:02:40 python3[931]:         resp = await server.wait_up(http=True, timeout=spawner.http_timeout)
May 24 03:02:40 python3[931]:       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/utils.py", line 197, in wait_for_http_server
May 24 03:02:40 python3[931]:         timeout=timeout
May 24 03:02:40 python3[931]:       File "/opt/tljh/hub/lib/python3.6/site-packages/jupyterhub/utils.py", line 155, in exponential_backoff
May 24 03:02:40 python3[931]:         raise TimeoutError(fail_message)
May 24 03:02:40 python3[931]:     TimeoutError: Server at http://127.0.0.1:57379/user/abc/ didn't respond in 30 seconds
May 24 03:02:40 python3[931]:
May 24 03:02:40 python3[931]: [I 2019-05-24 03:02:40.429 JupyterHub log:158] 200 GET /hub/api/users/abc/server/progress (abc@xx.xxx.xxx.xxx) 271.10ms
May 24 03:02:58 python3[931]: [I 2019-05-24 03:02:58.971 JupyterHub log:158] 200 GET /hub/home (abc@xx.xxx.xxx.xxx) 8.16ms
May 24 03:03:01 python3[931]: [I 2019-05-24 03:03:01.760 JupyterHub log:158] 302 GET /hub/spawn -> /user/abc/ (abc@xx.xxx.xxx.xxx) 7.97ms
May 24 03:03:01 python3[931]: [I 2019-05-24 03:03:01.799 JupyterHub log:158] 302 GET /user/abc/ -> /hub/user/abc/ (@xx.xxx.xxx.xxx) 0.46ms
May 24 03:03:01 python3[931]: [I 2019-05-24 03:03:01.884 JupyterHub systemdspawner:217] user:abc Unit jupyter-abc in a failed state. Resetting state.
May 24 03:03:01 python3[931]: Running as unit: jupyter-abc.service
```

**Comment by fm75** [comment] 2019-05-24 12:21
It appears that python3 is installed using apt-get [here](https://github.com/jupyterhub/the-littlest-jupyterhub/blob/master/bootstrap/bootstrap.py#L88). Apparently ubuntu's default install for python3 is still 3.6.7.

You could Google search "apt python 3.7" to see various instructions for installing 3.7.

**Comment by shireenrao** [comment] 2019-05-24 21:37
I finally got this to work but it was a bit of work and a few trials. This is what I did -

1. Start with a fresh ubuntu 18.04 on AWS
2. Install python3.7:
```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install python3.7
```
3. At this point I tried to make python3.7 the primary python by using 
```
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2
sudo update-alternatives --config python3
```
This broke apt. So I switched back to python3.6 as the primary python and decided to user python3.7 directly.
4. Cloned the tljh repository and updated lines 88 and 91 in bootstrap.py to reference python3.7 
5. Ran the tljh installer from my forked repo.
6 Here the user conda environment `/opt/tljh/user/bin/python` is again python 3.6 and the entire install is done under python3.6. As I could just update python here using `sudo /opt/tljh/user/bin/conda install python=3.7` I tried running that, but this time conda was failing. Some error which said the installed version was 4.5.* and it had to be 4.6.*. After trying to figure out a solution, found that I can fix this by installing conda 4.6 from the conda pkg cache
```
sudo /opt/tljh/user/bin/conda install /opt/tljh/user/pkgs/conda-4.6.14-py37_0.tar.bz2
```
This fixed conda and I was able to install python3.7 in user space.
```
sudo /opt/tljh/user/bin/conda install python=3.7
```
7. I realized I have to run the installer again as the bootstrap runs tljh.installer which had installed everything under `/opt/tljh/user/lib/python3.6`. After running the installer again I confirmed that all the requirements were installed under `/opt/tljh/user/lib/python3.7`    
8. Successfully logged in and and was able to create new notebooks and saw I was using python 3.7.2

This was kind of a brute force way of doing it. The problem right now is that the tljh.installer did not match the version of user python with the version of hub python.

**Comment by tekkenly** [comment] 2019-07-13 03:49
> I finally got this to work but it was a bit of work and a few trials. This is what I did -
> 
> 1. Start with a fresh ubuntu 18.04 on AWS
> 2. Install python3.7:
> 
> ```
> sudo add-apt-repository ppa:deadsnakes/ppa
> sudo apt-get update
> sudo apt-get install python3.7
> ```
> 
> 1. At this point I tried to make python3.7 the primary python by using
> 
> ```
> sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1
> sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2
> sudo update-alternatives --config python3
> ```
> 
> This broke apt. So I switched back to python3.6 as the primary python and decided to user python3.7 directly.
> 4. Cloned the tljh repository and updated lines 88 and 91 in bootstrap.py to reference python3.7
> 5. Ran the tljh installer from my forked repo.
> 6 After running the installer, I saw the user conda environment `/opt/tljh/user/bin/python` is again python 3.6 and the entire install is done under `/opt/tljh/user/lib/python3.6`. As I saw earlier I could just update user python using `sudo /opt/tljh/user/bin/conda install python=3.7` I tried running that, but this time conda broke. Some error which said the installed version was 4.5.* and it had to be 4.6.*. After trying to figure out a solution, found that I can fix this by installing conda 4.6 from the conda pkg cache
> 
> ```
> sudo /opt/tljh/user/bin/conda install /opt/tljh/user/pkgs/conda-4.6.14-py37_0.tar.bz2
> ```
> 
> This fixed conda and I was able to install python3.7 in user space.
> 
> ```
> sudo /opt/tljh/user/bin/conda install python=3.7
> ```
> 
> 1. I realized I have to run the installer again as the bootstrap runs tljh.installer which had installed everything under `/opt/tljh/user/lib/python3.6`. After running the installer again I confirmed that all the requirements were installed under `/opt/tljh/user/lib/python3.7`
> 2. Successfully logged in and and was able to create new notebooks and saw I was using python 3.7.2
> 
> This was kind of a brute force way of doing it. The problem right now is that the tljh.installer did not match the version of user python with the version of hub python.

thanks for providing these steps. I tried something else, and I installed with python 3.7 for hub and user envirments.

1, using original script to install, then stop services, remove /opt/tljh, deluser <adminuser>
2, I followed your first 3 steps
3, apt install python3.7-venv python3.7-dev
4, download bootstrap.py to local, remove apt update and add source operations which can cause error (because default python3 changed to version 3.7)
5, cat localbootstrap.py | |sudo -E python3 - --admin <admin-user-name>
6, remove /opt/tljh/user
7, edit /opt/tljh/hub/lib/python3.7/site-packages/tljh/installer.py, remove apt update and add source operations which can cause error, change conda version to 4.6.14, md5 to 718259965f234088d785cad1fbd7de03. also remove the line in localbootstrap.py which might redownload these scripts
8, cat localbootstrap.py | |sudo -E python3 - --admin <admin-user-name>

done!!!!!

**Comment by znicholls** [comment] 2019-07-27 06:10
Thanks @shireenrao and @tekkenly for your efforts! I can confirm that @tekkenly's solution worked for me and that I also broke apt when I tried @shireenrao's solution and hence think the solution suggested in #247 isn't actually usable. An upgrade to support Python3.7 natively would be great.

**Comment by mf-creator** [comment] 2019-11-11 17:57
I am also interested in any updates, I have attempted the same steps as illustrated by @tekkenly and it does not work for me.

**Comment by xavierliang** [comment] 2019-12-04 03:58
> I am also interested in any updates, I have attempted the same steps as illustrated by @tekkenly and it does not work for me.

Update conda, then install python3.7, works for me.

#sudo conda install anaconda
sudo conda update -all
sudo conda install python=3.7

**Comment by GeorgianaElena** [comment] 2020-02-03 07:40
Closed by https://github.com/jupyterhub/the-littlest-jupyterhub/pull/433

**Closed by GeorgianaElena** 2020-02-03 07:40 UTC
Labels: enhancement
